# Set update schedule for GitHub Actions

version: 2
registries:
  github-deps:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEPENDABOT_PAT }}
    
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
  - package-ecosystem: "gomod"
    directory: "/"
    registries:
      - github-deps
    ignore:
      - dependency-name: "golang.org/x/tools"
      - dependency-name: "google.golang.org/grpc"
    schedule:
      interval: "daily"
    groups:
      dependencies:
        dependency-type: "production"
        patterns:
          - "*"
