name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore Go cache
        uses: actions/cache@v3.2.4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Tests Acc
        env:
          SP_API_KEY: ${{ secrets.SP_API_KEY }}
          STATUSPAGE_PAGE_ID: ${{ secrets.STATUSPAGE_PAGE_ID }}
          STATUSPAGE_AUDIENCE_SPECIFIC_PAGE_ID: ${{ secrets.STATUSPAGE_AUDIENCE_SPECIFIC_PAGE_ID }}
          DD_API_KEY : ${{ secrets.DD_API_KEY }}
          DD_APP_KEY : ${{ secrets.DD_APP_KEY }}
          STATUSPAGE_PAGE_NAME : ${{ secrets.STATUSPAGE_PAGE_NAME }}
        run: |
          make cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3.1.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
