name: e2e

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  kind:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Restore Go cache
        uses: actions/cache@v2.1.6
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Tests Acc
        env:
          SP_API_KEY: ${{ secrets.SP_API_KEY }}
          STATUSPAGE_PAGE_ID: ${{ secrets.STATUSPAGE_PAGE_ID }}
          DD_API_KEY : ${{ secrets.DD_API_KEY }}
          DD_APP_KEY : ${{ secrets.DD_APP_KEY }}
        run: |
          make cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.5.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
